vich_uploader:
    db_driver: orm

    mappings:
        gallery:
            uri_prefix: /images/uploads/gallery
            upload_destination: '%kernel.project_dir%/public/images/uploads/gallery'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
